shell.run("clear")
print("Daniel Recovery Tool")
print("Reparando PC")
print("eliminando virus")
print("[---------------] 0%")
shell.run("rm /booterror.nfp")
sleep(1)
term.setCursorPos(1, 4)
print("[#####----------] 35%")
shell.run("rm /startup.lua")
sleep(1)
term.setCursorPos(1, 4)
print("[##########-----] 65%")
shell.run("mv /backup.lua /startup.lua")
sleep(1)
term.setCursorPos(1, 4)
print("[###############] Complete")
sleep(2)
print("Rebooting")
sleep(1)
os.reboot()
