shell.run("clear")
print("Trash Computer's Award Bios")
sleep(1)
write("Detecting RAM... ")
sleep(1)
print("Ok, You have 128 kB of RAM")
sleep(1)
write("Detecting OS... ")
sleep(1)
print("OK, Starting Class")
shell.run("/scripts/class.lua")
